package http

import (
	"net/http"

	"github.com/gorilla/mux"
	_ "github.com/singl3focus/t1_hackathon/backend/docs" // docs is generated by Swag CLI.
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

func (h *Handler) Router() http.Handler {
	public := mux.NewRouter()

	// [Public router]
	public.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.DeepLinking(true),
	)).Methods(http.MethodGet)

	public.HandleFunc("/healthy", h.Healthy).Methods(http.MethodGet)

	public.HandleFunc("/sprint/add", h.AddSprint).Methods(http.MethodPost)
	public.HandleFunc("/sprints/add", h.AddSprints).Methods(http.MethodPost)
	public.HandleFunc("/sprint/update-status", h.UpdateSprintStatus).Methods(http.MethodPost)
	public.HandleFunc("/sprint/all", h.GetAllSprints).Methods(http.MethodGet)
	public.HandleFunc("/sprint/task/all", h.GetAllSprintTasks).Methods(http.MethodGet)

	public.HandleFunc("/sprint/check-health", h.CheckSprintHealth).Methods(http.MethodGet)

	public.HandleFunc("/tasks/add", h.AddTasks).Methods(http.MethodPost)
	public.HandleFunc("/tasks/changes/add", h.AddTasksChanges).Methods(http.MethodPost)
	
	public.HandleFunc("/task/add", h.AddTask).Methods(http.MethodPost)
	public.HandleFunc("/task/update-status", h.UpdateTaskStatus).Methods(http.MethodPost)
	public.HandleFunc("/task/update-state", h.UpdateTaskState).Methods(http.MethodPost)
	public.HandleFunc("/task/get-by-ticketnumber", h.GetTaskByTicketNumber).Methods(http.MethodGet)
	
	public.HandleFunc("/task/changes/all", h.GetTaskChanges).Methods(http.MethodGet)

	return public
}
